import type { CarbonProject } from '@/lib/types/carbon';

export function generateComparisonPDF(projects: CarbonProject[]): void {
  const content = generatePDFContent(projects);
  const blob = new Blob([content], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `carbon-projects-comparison-${new Date().toISOString().split('T')[0]}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function generatePDFContent(projects: CarbonProject[]): string {
  const date = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let content = `Carbon Credit Projects Comparison\nGenerated: ${date}\n\n`;
  content += `Comparing ${projects.length} project(s)\n\n`;
  content += '='.repeat(80) + '\n\n';

  projects.forEach((project, index) => {
    content += `PROJECT ${index + 1}: ${project.name}\n`;
    content += '-'.repeat(80) + '\n';
    content += `Type: ${project.type}\n`;
    content += `Location: ${project.location}\n`;
    content += `Price per Ton: $${project.pricePerTon.toFixed(2)}\n`;
    content += `Vintage Year: ${project.vintageYear}\n`;
    content += `Verification: ${project.verificationStatus}\n`;
    content += `Available Supply: ${project.availableSupply.toFixed(2)} tons CO₂\n`;
    content += `Co-Benefits: ${project.coBenefits.join(', ')}\n`;
    content += `Description: ${project.description}\n`;
    content += '\n';
  });

  content += '='.repeat(80) + '\n';
  content += '\nThis comparison was generated by FarmCredit - Stellar Network\n';

  return content;
}
